language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_191b37c76924_key -iv $encrypted_191b37c76924_iv -in token.enc -out token -d
- chmod 600 token
- pwd
# Install base Android SDK
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
- wget http://dl.google.com/android/android-sdk_r22.0.5-linux.tgz
- tar xzf android-sdk_r22.0.5-linux.tgz
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
# install android build tools
- wget https://dl-ssl.google.com/android/repository/build-tools_r19.0.1-linux.zip
- unzip build-tools_r19.0.1-linux.zip -d $ANDROID_HOME
- mkdir -p $ANDROID_HOME/build-tools/
- mv $ANDROID_HOME/android-4.4.2 $ANDROID_HOME/build-tools/19.0.1
# Install required components.
- echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-19 --no-ui --force > /dev/null
- echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
- echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
before_script:
- ssh-keyscan -H shell.sf.net >> ~/.ssh/known_hosts
- ssh-keyscan -H shell.sourceforge.net >> ~/.ssh/known_hosts
- echo "exit" | ssh -i token -t ritchie_gmx_at,indiforjava@shell.sf.net create
- ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git clone git://git.code.sf.net/p/indiforjava/code indiforjava
- cd indiforjava
script: mvn clean install --settings ../settings.xml
after_success:
- mvn deploy --settings ../settings.xml
- mvn site site-deploy --settings ../settings.xml
env:
global:
- secure: "nPhZya2DxPualZILnwxyBG/OdVhltrv7VNNoubEi4C5NkIEC6QV/b0h9KbyUb/bw7htiX0tEuABiRbISWxj2aRomyIaWnWY9F25icT4vIY2qL66gNt9an+Fu/xOQfWcDlgwzVBHWaihzispwhV1X1HgDJ+j6dDmT1qbNUG7zrrg="
- secure: "kRRK94VXSCSB839o1gu0QnH+3H5sSeI8T4Cd3YF+FznYUTqq6zLQFXKz/eYmk4v+8Vq9c+s7shCx4qk1ayRa2O3NhSbpfypwigK3R29uukxHB7zuHU7IoXuUFGjr+MEGcrerhJCeOqQv6AVFFe22op5szmVlAiFLq9Q1Gr7JoQ8="
- secure: "qwxgqefHFlFt53kircBZTZUESrrXnvvL59rDfnGDf1q7i6AL1bIXgHAvX7OBCHtrtWDC9kr2yDMTDgmHP5mVyIRTJWPv2eDyKz7bsT2gsnjDhngb7G+wJvXPJVAcOnea7txyrduimuJFDIGWSQdEEVXqXEZqnWx1AZN3bdrjpno="
- secure: "LYsqaqbct8Zpm4ju1Ak0JDRT0SWDzUoBii9PhVeC2xairYvhcYZQ519csPq5lSQsDnH7AfEYdkuGJST6WWX1lBmaBa+pmqqHyiGZZMnPM0MWpcXLhEC3reB6xBUFbFGjZG9Q+oy9G8x5anD23oObz2nz7hPmyjLYUxfnRJEiSgo="
